version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      
volumes:
  postgres-db:
